# Generated by Django 6.0.1 on 2026-02-01 15:25

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student passport-size photo', null=True, upload_to=students.models.student_photo_path),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Complete residential address', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport number (unique identifier)', max_length=20, null=True, unique=True),
        ),
    ]
