# Generated by Django 4.2.17 on 2026-02-07 04:33

import cloudinary_storage.storage
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fix_passport_empty_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student passport-size photo', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=students.models.student_photo_path),
        ),
    ]
