# Generated by Django 4.2.17 on 2026-02-11 05:30

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student passport-size photo (JPG, PNG)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=students.models.student_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
