# Generated by Django 4.2.17 on 2026-02-04 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, user has a temporary password valid until this time (one-time use).', null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('email_attempted', models.BooleanField(default=False)),
                ('email_success', models.BooleanField(default=False)),
                ('sms_attempted', models.BooleanField(default=False)),
                ('sms_success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('result', models.CharField(choices=[('sent', 'Sent'), ('rate_limit_user', 'Rate limit (per user)'), ('rate_limit_ip', 'Rate limit (per IP)'), ('no_match', 'No matching student')], max_length=32)),
                ('user', models.ForeignKey(blank=True, help_text='Null if no matching student (non-enumeration).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password reset audit log',
                'verbose_name_plural': 'Password reset audit logs',
                'ordering': ['-requested_at'],
            },
        ),
    ]
