# Generated by Django 6.0.1 on 2026-02-01 14:45

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10TH_MARKSHEET', '10th Marksheet'), ('12TH_MARKSHEET', '12th Marksheet'), ('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('ADDITIONAL', 'Additional Document')], help_text='Type of document', max_length=20)),
                ('file', models.FileField(help_text='Upload document file', upload_to=documents.models.document_upload_path)),
                ('title', models.CharField(blank=True, help_text='Optional title for the document', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('student', 'document_type', 'title')},
            },
        ),
    ]
