# Generated by Django 4.2.17 on 2026-02-07 04:59

import cloudinary_storage.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload document file', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=documents.models.document_upload_path),
        ),
    ]
