# Generated by Django 4.2.17 on 2026-02-07 05:41

import cloudinary_storage.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Upload document file', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=documents.models.document_upload_path),
        ),
    ]
