# Generated by Django 4.2.17 on 2026-02-11 05:30

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Upload document file (PDF, JPG, PNG)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
