# Generated by Django 4.2.17 on 2026-02-11 06:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload document file (PDF, JPG, PNG)', max_length=255, null=True, verbose_name='file'),
        ),
    ]
